#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CYM____trimFL2016_loads
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ISU_Internal_CAN")]
	public partial class ITSsqlInternalCANDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public ITSsqlInternalCANDataContext() : 
				base(global::CYM____trimFL2016_loads.Properties.Settings.Default.ISU_Internal_CANConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ITSsqlInternalCANDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ITSsqlInternalCANDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ITSsqlInternalCANDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ITSsqlInternalCANDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TractorLocation> TractorLocations
		{
			get
			{
				return this.GetTable<TractorLocation>();
			}
		}
		
		public System.Data.Linq.Table<SugarWagonTractor> SugarWagonTractors
		{
			get
			{
				return this.GetTable<SugarWagonTractor>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TractorLocation")]
	public partial class TractorLocation
	{
		
		private string _ref_name;
		
		private System.Nullable<int> _ts_sec;
		
		private System.Nullable<System.DateTime> _GPS_DateTime;
		
		private System.Nullable<decimal> _Elev_Speed;
		
		private System.Nullable<long> _Cumulative_Volume_Scaled;
		
		private System.Nullable<decimal> _SCALE1_LBS;
		
		private System.Nullable<decimal> _CAN_NavigationBasedVehicleSpeed_kph;
		
		private System.Nullable<double> _CAN_Latitude;
		
		private System.Nullable<double> _CAN_Longitude;
		
		public TractorLocation()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ref_name", DbType="NVarChar(255)")]
		public string ref_name
		{
			get
			{
				return this._ref_name;
			}
			set
			{
				if ((this._ref_name != value))
				{
					this._ref_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ts_sec", DbType="Int")]
		public System.Nullable<int> ts_sec
		{
			get
			{
				return this._ts_sec;
			}
			set
			{
				if ((this._ts_sec != value))
				{
					this._ts_sec = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GPS_DateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> GPS_DateTime
		{
			get
			{
				return this._GPS_DateTime;
			}
			set
			{
				if ((this._GPS_DateTime != value))
				{
					this._GPS_DateTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Elev_Speed", DbType="Decimal(13,2)")]
		public System.Nullable<decimal> Elev_Speed
		{
			get
			{
				return this._Elev_Speed;
			}
			set
			{
				if ((this._Elev_Speed != value))
				{
					this._Elev_Speed = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cumulative_Volume_Scaled", DbType="BigInt")]
		public System.Nullable<long> Cumulative_Volume_Scaled
		{
			get
			{
				return this._Cumulative_Volume_Scaled;
			}
			set
			{
				if ((this._Cumulative_Volume_Scaled != value))
				{
					this._Cumulative_Volume_Scaled = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SCALE1_LBS", DbType="Decimal(17,5)")]
		public System.Nullable<decimal> SCALE1_LBS
		{
			get
			{
				return this._SCALE1_LBS;
			}
			set
			{
				if ((this._SCALE1_LBS != value))
				{
					this._SCALE1_LBS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CAN_NavigationBasedVehicleSpeed_kph", DbType="Decimal(17,6)")]
		public System.Nullable<decimal> CAN_NavigationBasedVehicleSpeed_kph
		{
			get
			{
				return this._CAN_NavigationBasedVehicleSpeed_kph;
			}
			set
			{
				if ((this._CAN_NavigationBasedVehicleSpeed_kph != value))
				{
					this._CAN_NavigationBasedVehicleSpeed_kph = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CAN_Latitude", DbType="Float")]
		public System.Nullable<double> CAN_Latitude
		{
			get
			{
				return this._CAN_Latitude;
			}
			set
			{
				if ((this._CAN_Latitude != value))
				{
					this._CAN_Latitude = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CAN_Longitude", DbType="Float")]
		public System.Nullable<double> CAN_Longitude
		{
			get
			{
				return this._CAN_Longitude;
			}
			set
			{
				if ((this._CAN_Longitude != value))
				{
					this._CAN_Longitude = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SugarWagonTractor")]
	public partial class SugarWagonTractor
	{
		
		private System.Nullable<int> _ts_sec;
		
		private System.Nullable<int> _ts_usec;
		
		private System.Nullable<byte> _channel;
		
		private string _mid;
		
		private string _pgn;
		
		private string _sa;
		
		private System.Nullable<byte> _dlc;
		
		private System.Nullable<byte> _d0;
		
		private System.Nullable<byte> _d1;
		
		private System.Nullable<byte> _d2;
		
		private System.Nullable<byte> _d3;
		
		private System.Nullable<byte> _d4;
		
		private System.Nullable<byte> _d5;
		
		private System.Nullable<byte> _d6;
		
		private System.Nullable<byte> _d7;
		
		private string _ref_name;
		
		public SugarWagonTractor()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ts_sec", DbType="Int")]
		public System.Nullable<int> ts_sec
		{
			get
			{
				return this._ts_sec;
			}
			set
			{
				if ((this._ts_sec != value))
				{
					this._ts_sec = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ts_usec", DbType="Int")]
		public System.Nullable<int> ts_usec
		{
			get
			{
				return this._ts_usec;
			}
			set
			{
				if ((this._ts_usec != value))
				{
					this._ts_usec = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_channel", DbType="TinyInt")]
		public System.Nullable<byte> channel
		{
			get
			{
				return this._channel;
			}
			set
			{
				if ((this._channel != value))
				{
					this._channel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mid", DbType="NVarChar(15)")]
		public string mid
		{
			get
			{
				return this._mid;
			}
			set
			{
				if ((this._mid != value))
				{
					this._mid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pgn", DbType="NVarChar(5)")]
		public string pgn
		{
			get
			{
				return this._pgn;
			}
			set
			{
				if ((this._pgn != value))
				{
					this._pgn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sa", DbType="NVarChar(2)")]
		public string sa
		{
			get
			{
				return this._sa;
			}
			set
			{
				if ((this._sa != value))
				{
					this._sa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dlc", DbType="TinyInt")]
		public System.Nullable<byte> dlc
		{
			get
			{
				return this._dlc;
			}
			set
			{
				if ((this._dlc != value))
				{
					this._dlc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_d0", DbType="TinyInt")]
		public System.Nullable<byte> d0
		{
			get
			{
				return this._d0;
			}
			set
			{
				if ((this._d0 != value))
				{
					this._d0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_d1", DbType="TinyInt")]
		public System.Nullable<byte> d1
		{
			get
			{
				return this._d1;
			}
			set
			{
				if ((this._d1 != value))
				{
					this._d1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_d2", DbType="TinyInt")]
		public System.Nullable<byte> d2
		{
			get
			{
				return this._d2;
			}
			set
			{
				if ((this._d2 != value))
				{
					this._d2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_d3", DbType="TinyInt")]
		public System.Nullable<byte> d3
		{
			get
			{
				return this._d3;
			}
			set
			{
				if ((this._d3 != value))
				{
					this._d3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_d4", DbType="TinyInt")]
		public System.Nullable<byte> d4
		{
			get
			{
				return this._d4;
			}
			set
			{
				if ((this._d4 != value))
				{
					this._d4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_d5", DbType="TinyInt")]
		public System.Nullable<byte> d5
		{
			get
			{
				return this._d5;
			}
			set
			{
				if ((this._d5 != value))
				{
					this._d5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_d6", DbType="TinyInt")]
		public System.Nullable<byte> d6
		{
			get
			{
				return this._d6;
			}
			set
			{
				if ((this._d6 != value))
				{
					this._d6 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_d7", DbType="TinyInt")]
		public System.Nullable<byte> d7
		{
			get
			{
				return this._d7;
			}
			set
			{
				if ((this._d7 != value))
				{
					this._d7 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ref_name", DbType="NVarChar(255)")]
		public string ref_name
		{
			get
			{
				return this._ref_name;
			}
			set
			{
				if ((this._ref_name != value))
				{
					this._ref_name = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
